/vesc_driver:
  ros__parameters:
    port: /dev/ttyACM0
    servo_min: 0.15
    servo_max: 0.85
    duty_cycle_min: -0.5
    duty_cycle_max: 0.5
    current_min: -7.5
    current_max: 7.5
    brake_min: 0.0
    brake_max: 200000.0
    speed_min: -10000.0
    speed_max: 10000.0
    position_min: 0.0
    position_max: 1000000.0
    use_servo_cmd: false  # Desabilitar servo via VESC
    publish_odom: true
    publish_tf: true
    odom_frame: odom
    base_frame: base_link