/vesc_driver:
  ros__parameters:
    port: /dev/ttyACM0  # Update this to your device path
    servo_min: 0.0
    servo_max: 1.0
    throttle_min: -1.0
    throttle_max: 1.0
    throttle_to_erpm_gain: 3000.0
    use_servo_cmd: true
    publish_odom: true
    publish_tf: true
    odom_frame: odom
    base_frame: base_link